import '/imports/client/controllers/MainComponent'
import '/imports/client/controllers/NavBarComponent'
import '../node_modules/bootstrap-sass/assets/javascripts/bootstrap.min.js'
import '/imports/client/controllers/StudentUpsertComponent'
import '/imports/client/controllers/LoginComponent'
import '/imports/client/controllers/FooterComponent'
import '/imports/client/controllers/StudentListComponent'
import '/imports/client/controllers/StudentViewComponent'
import '/imports/client/controllers/SubjectUpsertComponent'
import '/imports/client/controllers/TeacherUpsertComponent'
import '/imports/client/controllers/TeacherListComponent'
import '/imports/client/controllers/TeacherViewComponent'
import '/imports/client/controllers/CourseStudentEnrollComponent'
import '/imports/client/controllers/DegreeUpsertComponent'
import '/imports/client/controllers/ClassRecordComponent'

