import '/imports/client/controllers/MainComponent'
import '/imports/client/controllers/NavBarComponent'
import '/imports/client/controllers/StudentUpsertComponent'
import '/imports/client/controllers/LoginComponent'
import '/imports/client/controllers/FooterComponent'
