image: node:4.2.2

stages:
  - test

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

services:
  - mongo

variables:
  MONGO_URI: "mongodb://mongo/coedb"
  NODE_ENV: 'ci'

all_tests:
  stage: test
  script:
    - npm install && npm install --only=dev
    - npm run ci
