image: node:7.2.1

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

services:
  - mongo

variables:
  MONGO_URI: "mongodb://mongo/coedb"
  NODE_ENV: 'ci'

all_tests:
  script:
    - npm install && npm install --only=dev
    - curl https://install.meteor.com/?release=1.4.1.1 | sh && export LC_All=en_US.UTF-8 && MONGO_URL=mongodb://mongo/coedb meteor test --once --driver-package dispatch:mocha-phantomjs --unsafe-perm
