import '/imports/both/models/Student.js'
import '/imports/both/models/User.js'
import '/imports/both/models/Subject.js'
import '/imports/both/models/Course.js'
import '/imports/both/models/Role.js'
import '/imports/both/models/Activity.js'
